version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=steppe_db
      - POSTGRES_USER=steppe_user
      - POSTGRES_PASSWORD=steppe_pass

  redis:
    image: redis:alpine
    restart: always

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: .
    restart: always
    command: celery -A steppe_clone worker -l info
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data: